P = []
def add(pid, brand, name, cat, cu, rx, size=None, exclude=None, prefer=None, note=None, **over):
    """cu: compare unit: 'l' (per liter), 'kg' (per kg), 'st' (per unit), 'wb' (per wash), 'rol' (per roll).
    Names here are the Dutch working names; build_data.py replaces them with the English NAME_EN labels."""
    P.append(dict(id=pid, brand=brand, name=name, category=cat, cu=cu, rx=rx, size=size, exclude=exclude, prefer=prefer, note=note, over=over))
X_COMMON = r'multipack|voordeelpak|voordeelverpakking|\d+-pack|\d+ x |x \d|pakket|giga|xxl|dubbelpak'
# ---------------- PERSONAL CARE (verzorging) ----------------
add('nivea-fresh-natural-deo','NIVEA','Fresh Natural deodorant spray','verzorging','l', r'nivea.*fresh natural', r'150', X_COMMON+r'|roll|stick|douche')
add('nivea-men-dry-impact-deo','NIVEA MEN','Men Dry Impact anti-transpirant spray','verzorging','l', r'nivea.*men.*dry impact|nivea deospray men dry impact', r'150', X_COMMON+r'|roll|stick|douche')
add('dove-original-deo','Dove','Original / Advanced Care Original deodorant spray','verzorging','l', r'dove.*original', r'150', X_COMMON+r'|men|roll|stick|douche|zeep|shower|beauty|cream|crème|0%|0 %|zero|72h|6 stuk|x 6|x6')
add('axe-africa-bodyspray','Axe','Africa deodorant bodyspray','verzorging','l', r'\baxe\b.*africa', r'150', X_COMMON+r'|douche|shower|gel|roll|stick')
add('rexona-men-cobalt-deo','Rexona','Men Cobalt Dry anti-transpirant spray','verzorging','l', r'rexona.*cobalt', r'150', X_COMMON+r'|roll|stick|2-pack|2 x|max pro|maximum')
add('sanex-sensitive-deo','Sanex','Dermo/Derma Sensitive deodorant spray','verzorging','l', r'sanex.*sensitive', r'200|150', X_COMMON+r'|zero|roll|stick|douche|shower|men')
add('dove-men-clean-comfort-douche','Dove Men+Care','Clean Comfort douchegel','verzorging','l', r'dove.*(men|for men).*clean comfort.*(douche|shower|gel|wash)|dove.*(douche|shower).*(men|for men).*clean comfort', r'250|400', X_COMMON+r'|deo|spray|stick|roll')
add('palmolive-naturals-amandel-douche','Palmolive','Naturals amandel douchegel / douchecrème','verzorging','l', r'palmolive.*amandel.*(douche|bad)|palmolive.*(douche|bad).*amandel', r'250', X_COMMON+r'|zeep|hand|shampoo|scheer|schuim', prefer=r'250')
add('palmolive-amandel-handzeep','Palmolive','Naturals amandel handzeep (pomp)','verzorging','l', r'palmolive.*amandel', r'300|250|500', X_COMMON+r'|douche|bad|shampoo|navul', prefer=r'zeep|hand')
add('andrelon-classic-iedere-dag','Andrélon','Classic Iedere Dag shampoo','verzorging','l', r'andr[ée]lon.*iedere dag', r'300|400|250', X_COMMON+r'|conditioner|cr[eè]me|droog|\bmen\b')
add('head-shoulders-classic','Head & Shoulders','Classic anti-roos shampoo','verzorging','l', r'head\s*&\s*shoulders.*classic', r'250|300|400', X_COMMON+r'|2.?in.?1|2in1|conditioner')
add('elvive-color-vive-shampoo',"L'Oréal Elvive",'Color-Vive shampoo','verzorging','l', r'(elvive|elseve).*color.?vive', r'250|300', X_COMMON+r'|conditioner|cr[eè]me|masker|balsem')
add('fructis-shampoo','Garnier Fructis','Fructis shampoo (Damage Repair e.a.)','verzorging','l', r'fructis.*shampoo', r'250|300', X_COMMON+r'|conditioner')
add('colgate-caries-protection','Colgate','Caries/Cavity Protection tandpasta','verzorging','l', r'colgate.*(caries|cari[eë]s|cavity)', r'75', X_COMMON+r'|kids|junior|3 x|2 x')
add('oralb-3d-white-arctic-fresh','Oral-B','3D White Arctic Fresh tandpasta','verzorging','l', r'oral-?b.*(arctic|artic) fresh', r'75', X_COMMON)
add('sensodyne-fresh-mint','Sensodyne','Fresh Mint tandpasta','verzorging','l', r'sensodyne.*fresh mint', r'75', X_COMMON+r'|2-pack|2 x|gel')
add('listerine-cool-mint','Listerine','Cool Mint mondwater','verzorging','l', r'listerine.*(cool ?mint)', r'500|0,5|600|1 l|250', X_COMMON+r'|mild|zero|95')
add('gillette-blue3-wegwerp','Gillette','Blue3 wegwerpmesjes','verzorging','st', r'gillette blue ?3|gillette blue3', r'\d', X_COMMON)
add('always-ultra-normal','Always','Ultra maandverband Normal (met vleugels)','verzorging','st', r'always.*ultra.*(normal|normaal)|always.*(normal|normaal).*ultra', r'\d', X_COMMON+r'|night|long|super|discreet|dailies|inleg')
add('always-dailies-normal','Always','Dailies inlegkruisjes Normal','verzorging','st', r'always.*(dailies|daily|to go).*(normal|normaal)|always.*(normal|normaal).*(inlegkruisje)', r'\d', r'giga|large|long|cotton|fresh|extra|discreet')
# ---------------- HOUSEHOLD (huishouden) ----------------
add('ariel-4in1-pods','Ariel','4-in-1 pods (color / ultra)','huishouden','wb', r'ariel.*(4-?in-?1|4in1).*pods|ariel.*pods.*(4-?in-?1|4in1)|ariel \+ pods 4in1', r'\d', X_COMMON+r'|unstoppables|black|zwart|hygiene|actief|active', prefer=r'color|kleur')
add('ariel-3in1-pods-color','Ariel','3-in-1 pods Color','huishouden','wb', r'ariel.*(3-?in-?1|3in1).*pods.*(color|kleur)|ariel.*pods.*(3-?in-?1|3in1).*(color|kleur)|ariel 3in1 pods color|ariel pods color', r'\d', X_COMMON+r'|big one|\+')
add('ariel-vloeibaar-color','Ariel','Vloeibaar wasmiddel Color','huishouden','wb', r'ariel.*(vloeibaar|wasmiddel|liquid).*(color|kleur)|ariel.*(color|kleur).*(vloeibaar|wasmiddel|liquid)|ariel liquid kleur|ariel color', r'\d', X_COMMON+r'|pods|capsule|poeder|powder|unstoppables|stuks|\bst\b|complete')
add('omo-vloeibaar-kleur','Omo','Vloeibaar wasmiddel Kleur/Color','huishouden','wb', r'\bomo\b.*(vloeibaar|liquid|wasmiddel)', r'\d', X_COMMON+r'|poeder|powder|capsule|caps|wit\b|white', prefer=r'kleur|color')
add('robijn-klein-krachtig-color','Robijn','Klein & Krachtig / Color vloeibaar wasmiddel','huishouden','wb', r'robijn.*(klein\s*&\s*krachtig|color|kleur).*(wasmiddel|vloeibaar)|robijn.*(wasmiddel|vloeibaar).*(color|kleur|klein)|robijn color|robijn klein', r'\d', X_COMMON+r'|capsule|caps|poeder|wasverzachter|stralend|wit\b|zwart|black|perfect match|doekjes|doekje|kokos|bohemian|paradise|pink|spa sensation|tropical|morgenfris')
add('robijn-wasverzachter','Robijn','Wasverzachter (Rosé Chique / Zwitsal / Morgenfris)','huishouden','wb', r'robijn.*wasverzachter', r'\d', X_COMMON+r'|navul|zak\b', prefer=r'zwitsal')
add('vanish-oxi-gel','Vanish','Oxi Action vlekverwijderaar gel (gekleurde was)','huishouden','l', r'vanish.*(gel|wasbooster|oxi)', r'\d', X_COMMON+r'|poeder|powder|spray|200 ?ml|tapijt|trigger|white|whitening|gram|\bg\b|pakket|powergel|power gel|gold|tough', prefer=r'gekleurd|color|kleur|gel')
add('dreft-afwasmiddel-original','Dreft','Afwasmiddel Original / Max Power Original','huishouden','l', r'dreft.*afwas.*(original|classic)|dreft (original|classic).*afwas|dreft afwasmiddel$', r'\d', X_COMMON+r'|navul|platinum|quick|lemon|citroen|eucalyptus|lavend')
add('dreft-platinum-vaatwastabs','Dreft','Platinum vaatwastabletten (all-in-one)','huishouden','st', r'dreft.*platinum', r'\d', X_COMMON+r'|afwas|gel|poeder|spoelmiddel|jungle')
add('finish-quantum-vaatwastabs','Finish','Quantum / All in 1 vaatwastabletten','huishouden','st', r'finish.*(quantum|all.?in.?1|powerball|ultimate)', r'\d', X_COMMON+r'|glansspoel|reiniger|zout|gel|poeder|max in 1 plus|all in 1 power|power\b')
add('antikal-kalkreiniger','Antikal','Kalkreiniger (spray / gel)','huishouden','l', r'antikal.*(spray|gel|kalk|reiniger)', r'\d', X_COMMON+r'|tablet|douchewand|douche express|badkamer', prefer=r'original|kalkreiniger|spray')
add('wc-eend-fresh-discs','WC-Eend','Fresh Discs houder/starterkit','huishouden','st', r'wc-?\s?eend.*fresh discs', r'\d', X_COMMON+r'|navul|duo', prefer=r'houder|starter')
add('page-toiletpapier','Page','Toiletpapier (Original / Kussenzacht / Betrouwbaar Schoon)','huishouden','rol', r'\bpage\b.*(toiletpapier|wc-?papier|kussenzacht|original|betrouwbaar)', r'\d', X_COMMON+r'|vochtig|gerecycled|recycled|compleet|schoon en zacht|luchtverf|maxi', prefer=r'original|kussenzacht|betrouwbaar')
add('edet-soft-toiletpapier','Edet','Soft toiletpapier','huishouden','rol', r'\bedet\b.*(soft|toiletpapier|wc-?papier)', r'\d', X_COMMON+r'|vochtig|luchtverfrisser|easypull|keuken|navul|zakdoek|comfort plus', prefer=r'soft')
add('page-vochtig-toiletpapier','Page','Vochtig toiletpapier (Aloë vera / doorspoelbaar)','huishouden','st', r'\bpage\b.*vochtig', r'\d', X_COMMON+r'|kids|junior|maxi|1 stuks', prefer=r'aloe|aloë|fresh|doorspoelbaar')
# ---------------- FOOD & DRINKS (eten-drinken) ----------------
add('coca-cola-original','Coca-Cola','Original Taste (vergeleken per liter)','eten-drinken','l', r'coca.?cola (original|regular)|coca.?cola$|coca cola regular|coca-cola original taste', r'1,5|1.5|1 l|1 liter|375|330|500', X_COMMON+r'|zero|light|cherry|vanilla|lemon|4 x|6 x|12 x|24 x|blik|can', prefer=r'1,5|1.5')
add('coca-cola-zero','Coca-Cola','Zero Sugar (vergeleken per liter)','eten-drinken','l', r'coca.?cola.*zero', r'1,5|1.5|1 l|1 liter|375|330|500', X_COMMON+r'|cherry|vanilla|lemon|4 x|6 x|12 x|24 x|blik|can', prefer=r'1,5|1.5')
add('fanta-orange','Fanta','Orange (vergeleken per liter)','eten-drinken','l', r'fanta.*(orange|sinas)|fanta$', r'1,5|1.5|1 l|1 liter|375|330|500', X_COMMON+r'|zero|light|exotic|lemon|cassis|4 x|6 x|12 x|blik|can|gekoeld', prefer=r'1,5|1.5')
add('red-bull-250','Red Bull','Energy Drink 250 ml (per blikje)','eten-drinken','st', r'red bull.*(energy)|red bull$', r'250|0,25|25 ?cl', X_COMMON+r'|sugar|zero|suikervrij|tropical|watermel|red edition|white|blue|yellow|apricot|4 x|6 x|8 x|12 x|24 x|-pack|\+1|7\+')
add('monster-energy-500','Monster','Energy 500 ml (per blikje)','eten-drinken','st', r'monster.*energy', r'500|553|0,5', X_COMMON+r'|ultra|zero|juiced|mango|4 x|6 x|12 x|-pack|4x|rio|punch|pipeline|pacific|khaotic|mule|nitro|reserve', prefer=r'green|original|energy$')
add('doritos-nacho-cheese','Doritos','Nacho Cheese','eten-drinken','kg', r'doritos.*nacho cheese', r'\d', X_COMMON+r'|bits|30 g|33 g|40 g|snackbox|dip|party')
add('pringles-original','Pringles','Original','eten-drinken','kg', r'pringles.*original', r'165|175|185|200', X_COMMON+r'|40 g|70 g|snack')
add('lays-naturel',"Lay's",'Naturel chips','eten-drinken','kg', r"lay'?s.*(naturel|natural)", r'\d', X_COMMON+r'|bugles|oven|light|sensations|max|mini|40 g|45 g|snack')
add('haribo-goudberen','Haribo','Goudberen','eten-drinken','kg', r'haribo.*(goudber|goldb)', r'\d', X_COMMON+r'|mini|zak\b|kg|1 kg|zuur|sour|8 x|10 x')
add('douwe-egberts-aroma-rood-500','Douwe Egberts','Aroma Rood filterkoffie 500 g','eten-drinken','kg', r'douwe egberts.*aroma rood', r'500', X_COMMON+r'|bonen|grove|dubbelpak|2 x|decaf|pads|cups')
add('nutella-hazelnootpasta','Nutella','Hazelnootpasta','eten-drinken','kg', r'nutella', r'\d', X_COMMON+r'|go|b-ready|biscuit|koek|mini|portie|1 kg|750|630')
add('calve-pindakaas-350','Calvé','Pindakaas (naturel) 350 g','eten-drinken','kg', r'calv[ée].*pindakaas', r'350', X_COMMON+r'|100%|crunchy|creamy|light|extra|stukjes|pinda-?kokos|met stukjes|halfvol|nootjes|karamel|jam')
add('heinz-tomato-ketchup','Heinz','Tomato Ketchup (per liter)','eten-drinken','l', r'heinz.*(tomaten|tomato) ketchup', r'\d', X_COMMON+r'|zero|50%|less|minder|hot|curry|bio|topdown|sachet|portie', prefer=r'570|0,57|500|875|0,88')
add('fernandes-cherry-bouquet','Fernandes','Cherry Bouquet (per liter)','eten-drinken','l', r'fernandes.*cherry', r'1,5|1.5|330|250|4 x', X_COMMON+r'|zero|4-pack|4 x|6 x', prefer=r'1,5|1.5')
add('dr-pepper-vanilla-float','Dr Pepper','Vanilla/Vanille Float 330 ml','eten-drinken','l', r'dr\.?\s*pepper.*(vanil)', r'330|0,33', X_COMMON+r'|6-pack|6 x|4 x')
add('kelloggs-cornflakes',"Kellogg's",'Corn Flakes','eten-drinken','kg', r"kellogg'?s.*corn ?flakes", r'\d', X_COMMON+r'|crunchy|nut|honey|choco|frosties|1 kg|750|500 g x')
add('cup-a-soup-tomaat','Knorr / Unox','Cup-a-Soup tomaat 3-pack','eten-drinken','st', r'cup-?a-?soup.*tomaat', r'\d', X_COMMON+r'|10-pack|10 x|chinese|cr[eè]me|zero|kruidig|extra')
add('bifi-original','Bifi','Original worstjes (multipack)','eten-drinken','st', r'bifi.*(original|the original)|bifi original', r'\d', X_COMMON.replace('|\\d+-pack','')+r'|mini|roll|bbq|hot|carazza|xxl|100 g')
